version: '3'

services:     
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    tty: true
    networks:
      - fullcycle
    ports: 
      - "8080:80"
    depends_on: 
      - app
  
  app:
    build: 
      context: ./node
    container_name: app
    tty: true
    volumes: 
      - ./node:/app
    networks:
      - fullcycle
    command: bash -c "npm install && node app.js"
    depends_on: 
      mysql:
        condition: service_healthy
      
  mysql:
    image: mysql
    container_name: mysql
    tty: true
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fullcycle
      - MYSQL_USER=fullcycle
      - MYSQL_PASSWORD=fullcycle
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 20s
      retries: 3
    networks:
      - fullcycle

networks: 
  fullcycle:
    driver: bridge
